//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHC.UROCare.UROCareDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Andrology
    {
        public int Andrology_ID { get; set; }
        public int Patient_ID { get; set; }
        public int Gu_No { get; set; }
        public int Gu_Year { get; set; }
        public string Complaint { get; set; }
        public string Married_Since { get; set; }
        public string Signi_Illness { get; set; }
        public string Treatment_Taken { get; set; }
        public string Alcoholism { get; set; }
        public string Fever { get; set; }
        public string Smoking { get; set; }
        public string Mumps_Orchits { get; set; }
        public string Erection { get; set; }
        public string Ejaculation { get; set; }
        public string General_Exam { get; set; }
        public string Virilization { get; set; }
        public string PA { get; set; }
        public string PR { get; set; }
        public string VAS { get; set; }
        public string Varicocele { get; set; }
        public string Testis { get; set; }
        public string Epididymis { get; set; }
        public string Semen_Analysis { get; set; }
        public string SR_FSH { get; set; }
        public string LH { get; set; }
        public string Testosterone { get; set; }
        public string Prolactin { get; set; }
        public string Testi_Biopsy { get; set; }
        public string Others { get; set; }
        public string Treatment_Given { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Create_Dte { get; set; }
        public string Modify_By { get; set; }
        public Nullable<System.DateTime> Modify_Dte { get; set; }
    
        public virtual Patient_Info Patient_Info { get; set; }
    }
}
