//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHC.UROCare.UROCareDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctors_List
    {
        public Doctors_List()
        {
            this.Patient_Info = new HashSet<Patient_Info>();
            this.Operation_Dtls = new HashSet<Operation_Dtls>();
        }
    
        public int ID { get; set; }
        public string Doctor_Name { get; set; }
        public string At_Post { get; set; }
        public string Taluka { get; set; }
        public string District { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> Birth_Dte { get; set; }
        public string Dr_Email { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Create_Dte { get; set; }
        public string Modify_By { get; set; }
        public Nullable<System.DateTime> Modify_Dte { get; set; }
    
        public virtual ICollection<Patient_Info> Patient_Info { get; set; }
        public virtual ICollection<Operation_Dtls> Operation_Dtls { get; set; }
    }
}
