//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHC.UROCare.UROCareDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Investigation
    {
        public int Investigation_ID { get; set; }
        public int Patient_ID { get; set; }
        public int Gu_No { get; set; }
        public int Gu_Year { get; set; }
        public string Urine { get; set; }
        public string HB { get; set; }
        public string TC { get; set; }
        public string DC { get; set; }
        public string SR_NA_Plus { get; set; }
        public string SR_K_Plus { get; set; }
        public string SR_CA_Plus { get; set; }
        public string SR_Uric_Acid { get; set; }
        public string HIV { get; set; }
        public string SR_Creat { get; set; }
        public string HBS_AG { get; set; }
        public string BUL { get; set; }
        public string ESR { get; set; }
        public string Urine_Chyle { get; set; }
        public string BSL { get; set; }
        public string USG { get; set; }
        public string KUB { get; set; }
        public string IVP { get; set; }
        public string RGU { get; set; }
        public string MCU { get; set; }
        public string NCHCT { get; set; }
        public string DTPA_Reno { get; set; }
        public string TRUS { get; set; }
        public string Sr_PSA { get; set; }
        public string CT_Scan { get; set; }
        public string Urine_CS { get; set; }
        public string Volume { get; set; }
        public string PH { get; set; }
        public string Calcium { get; set; }
        public string Uric_Acid { get; set; }
        public string Sodium { get; set; }
        public string Oxalate { get; set; }
        public string Citrate { get; set; }
        public string Sulfate { get; set; }
        public string Phosphorous { get; set; }
        public string Stone_Analysis { get; set; }
        public string Bone_Scan { get; set; }
        public string MRI { get; set; }
        public string Others { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Create_Dte { get; set; }
        public string Modify_By { get; set; }
        public Nullable<System.DateTime> Modify_Dte { get; set; }
    
        public virtual Patient_Info Patient_Info { get; set; }
    }
}
