//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHC.UROCare.UROCareDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_Examination
    {
        public int Examination_ID { get; set; }
        public int Patiend_ID { get; set; }
        public int Gu_No { get; set; }
        public int Gu_Year { get; set; }
        public string G_E { get; set; }
        public string Pulse { get; set; }
        public string BP { get; set; }
        public string Weight { get; set; }
        public string Abdomen { get; set; }
        public string Genitalia { get; set; }
        public string Anal_Tone { get; set; }
        public string BCR { get; set; }
        public string Prostate { get; set; }
        public string PR_Others { get; set; }
        public string P_S { get; set; }
        public string P_V { get; set; }
        public string CNS { get; set; }
        public string CVS { get; set; }
        public string R_S { get; set; }
        public string Others { get; set; }
        public string Remarks { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Create_Dte { get; set; }
        public string Modify_By { get; set; }
        public Nullable<System.DateTime> Modify_Dte { get; set; }
    
        public virtual Patient_Info Patient_Info { get; set; }
    }
}
