//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHC.UROCare.UROCareDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_Info
    {
        public Patient_Info()
        {
            this.Andrologies = new HashSet<Andrology>();
            this.ESWLs = new HashSet<ESWL>();
            this.Follow_Up = new HashSet<Follow_Up>();
            this.Investigations = new HashSet<Investigation>();
            this.IPDs = new HashSet<IPD>();
            this.Operation_Dtls = new HashSet<Operation_Dtls>();
            this.Patient_Examination = new HashSet<Patient_Examination>();
            this.Treatement_Dtls = new HashSet<Treatement_Dtls>();
            this.Treatment_Advised = new HashSet<Treatment_Advised>();
            this.UDS = new HashSet<UD>();
            this.Urology_History = new HashSet<Urology_History>();
            this.XRayImages = new HashSet<XRayImage>();
        }
    
        public int Patient_ID { get; set; }
        public int Gu_No { get; set; }
        public int Gu_Year { get; set; }
        public System.DateTime Reg_Date { get; set; }
        public string Salutation { get; set; }
        public string Patient_Name { get; set; }
        public Nullable<short> Age_Yr { get; set; }
        public Nullable<short> Age_Mnth { get; set; }
        public Nullable<short> Sex { get; set; }
        public string Occupation { get; set; }
        public Nullable<int> DR_No { get; set; }
        public string At_Post { get; set; }
        public string Town { get; set; }
        public string District { get; set; }
        public string State { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string OPD_Diagnosis { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Create_Dte { get; set; }
        public string Modify_By { get; set; }
        public Nullable<System.DateTime> Modify_Dte { get; set; }
    
        public virtual ICollection<Andrology> Andrologies { get; set; }
        public virtual Doctors_List Doctors_List { get; set; }
        public virtual ICollection<ESWL> ESWLs { get; set; }
        public virtual ICollection<Follow_Up> Follow_Up { get; set; }
        public virtual ICollection<Investigation> Investigations { get; set; }
        public virtual ICollection<IPD> IPDs { get; set; }
        public virtual ICollection<Operation_Dtls> Operation_Dtls { get; set; }
        public virtual ICollection<Patient_Examination> Patient_Examination { get; set; }
        public virtual ICollection<Treatement_Dtls> Treatement_Dtls { get; set; }
        public virtual ICollection<Treatment_Advised> Treatment_Advised { get; set; }
        public virtual ICollection<UD> UDS { get; set; }
        public virtual ICollection<Urology_History> Urology_History { get; set; }
        public virtual ICollection<XRayImage> XRayImages { get; set; }
    }
}
