//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHC.UROCare.UROCareDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription_Template
    {
        public int ID { get; set; }
        public string Template_Name { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Dte { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Dte { get; set; }
    }
}
