//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHC.UROCare.UROCareDataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UROCareEntities : DbContext,IUROCareEntities
    {
        public UROCareEntities()
            : base("name=UROCareEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Andrology> Andrologies { get; set; }
        public DbSet<Doctors_List> Doctors_List { get; set; }
        public DbSet<ESWL> ESWLs { get; set; }
        public DbSet<Follow_Up> Follow_Up { get; set; }
        public DbSet<Investigation> Investigations { get; set; }
        public DbSet<IPD> IPDs { get; set; }
        public DbSet<Operation_Dtls> Operation_Dtls { get; set; }
        public DbSet<Param_Dtls> Param_Dtls { get; set; }
        public DbSet<Param_Master> Param_Master { get; set; }
        public DbSet<Patient_Examination> Patient_Examination { get; set; }
        public DbSet<Patient_Info> Patient_Info { get; set; }
        public DbSet<Prescription_Template> Prescription_Template { get; set; }
        public DbSet<Treatement_Dtls> Treatement_Dtls { get; set; }
        public DbSet<Treatment_Advised> Treatment_Advised { get; set; }
        public DbSet<UD> UDS { get; set; }
        public DbSet<Urology_History> Urology_History { get; set; }
        public DbSet<User_Master> User_Master { get; set; }
        public DbSet<XRayImage> XRayImages { get; set; }
    }
}
