//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHC.UROCare.UROCareDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urology_History
    {
        public int History_ID { get; set; }
        public int Patient_ID { get; set; }
        public int Gu_No { get; set; }
        public int Gu_Year { get; set; }
        public string Chief_Compl { get; set; }
        public string Frequency { get; set; }
        public string Hesitancy { get; set; }
        public string Nocturia { get; set; }
        public string Poor_Stream { get; set; }
        public string Urgency { get; set; }
        public string Intermittency { get; set; }
        public string Dysuria { get; set; }
        public string Straining { get; set; }
        public string Pyuria { get; set; }
        public string Sense_Incompl_Void { get; set; }
        public string Lithiuria { get; set; }
        public string Terminal_Dribbling { get; set; }
        public string Chyluria { get; set; }
        public string Urge_Inc { get; set; }
        public string Fever { get; set; }
        public string Stress_Inc { get; set; }
        public string IPSS { get; set; }
        public string BPI { get; set; }
        public string Pain { get; set; }
        public string Others { get; set; }
        public string Medication { get; set; }
        public string Personal { get; set; }
        public string Surgery { get; set; }
        public string MH { get; set; }
        public string Allergies { get; set; }
        public string OB_GY { get; set; }
        public string Past { get; set; }
        public string Family { get; set; }
        public string Hematuria { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Create_Dte { get; set; }
        public string Modify_By { get; set; }
        public Nullable<System.DateTime> Modify_Dte { get; set; }
    
        public virtual Patient_Info Patient_Info { get; set; }
    }
}
