//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHC.UROCare.UROCareDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class XRayImage
    {
        public int Image_ID { get; set; }
        public int Patient_ID { get; set; }
        public int GU_No { get; set; }
        public int GU_Year { get; set; }
        public int Sr_No { get; set; }
        public Nullable<int> Image_Type { get; set; }
        public Nullable<System.DateTime> Image_Date { get; set; }
        public string Comments { get; set; }
        public byte[] Image_Captured { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Dte { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Dte { get; set; }
    
        public virtual Patient_Info Patient_Info { get; set; }
    }
}
